name: CItest
on: [ workflow_dispatch ]

jobs:
  testjob:
    name: Use Linux commands
    runs-on: ubuntu-latest

    steps:
    - name: check echo
      run: echo Hello, world!
    - name: check out
      uses: actions/checkout@v6
    - name: Show current directory
      run: |
        echo "Current path:"
        pwd
        echo "Directory list:"
        ls -la

    # Sets up MATLAB on a GitHub-hosted runner
    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: R2023a
        products: >
            Simulink
            Stateflow
            Simulink_Test
            Parallel_Computing_Toolbox
